# This is a continuous action workflow for checking style.
name: CI

# Controls when the action will run. Triggers the workflow on push
# events but only for the master branch. Triggers on all pull requests.
on:
  push:
    branches: [ master ]
  pull_request:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a two jobs.
  # The first checks the code's style. The second builds & tests the library.
  check-style:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v2
    
    - name: Setup Python
      uses: actions/setup-python@v2
      with:
        python-version: 2.7
    
    - name: Install clang-format
      run: |
        sudo apt-get install clang-format
    
    - name: Check style
      run: |
        "${GITHUB_WORKSPACE}/third_party/run_clang_format/run-clang-format.py" -r lib test third_party/spdk_defs

